### PR TITLE
add meson build

### PR DESCRIPTION
**Pull request by coderkalyan**
Adds support for the meson build system.

### CODE REVIEW

**Comment by lucasdemarchi** [comment]
Cool. I tried some time ago but got stuck in a "bug" in meson where it was not possible to include the generated headers from mavlink. Has anything changed recently in meson that allows that?  See branch https://github.com/intel/mavlink-router/commits/meson for what I had.

**Comment by lucasdemarchi** [comment]
This was the issue: https://github.com/mesonbuild/meson/issues/1855

**Comment by lucasdemarchi** [comment]
@coderkalyan any update here ?

**Comment by coderkalyan** [comment]
@lucasdemarchi sorry for the late reply. I encountered similar issues to your attempt, so when I created this PR I circumvented the problem by running a command through meson instead of a generator/custom target. It builds but I know this isn't ideal so I'm working on trying to fix the issue

**Comment by lucasdemarchi** [comment]
@coderkalyan  but I don't see how it solves the problem. If we build multiple times, change the mavlink headers, it will have problems autobuilding, unless we call the specific commands agains.

I'd love to switch to meson, but it seems they are not very friendly to generating headers like we need.

**Comment by coderkalyan** [comment]
@lucasdemarchi Understood, I'll try to dig into this more or ask on the meson support channel/issue tracker.

**Comment by lucasdemarchi** [comment]
@coderkalyan See #291

**Comment by coderkalyan** [comment]
Alright, makes sense. I'll update this when I get a chance.

**Comment by lucasdemarchi** [comment]
See #294

**Pull request closed without merging**
